version: '3.3'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  rq_worker:
    build:
      context: .
      dockerfile: Dockerfile.rq_worker
    volumes:
      - .:/pic_search
    working_dir: /pic_search
    command: ["rq", "worker","--url","redis://redis:6379/0"]
    depends_on:
      - redis

  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - qdrant
      - redis
      - rq_worker

volumes:
  qdrant_data:
